services:
  # Base configuration for the application
  app-base: &app-base
    image: ghcr.io/shaogme/nixos-dockers/vscode-rust:latest
    environment:
      - ROOT_PASSWORD=root # Set your secure password here
    security_opt:
      - seccomp:unconfined # Required for some low-level operations
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    tty: true

  # Develop mode: Mounts local directory for hot-reloading (Default)
  dev:
    <<: *app-base
    container_name: dev
    volumes:
      - .:/root/workspace
      # Mount host SSH public key to temporary location
      - ${USERPROFILE}/.ssh/id_ed25519.pub:/tmp/id_ed25519.pub:ro
    ports:
      # SSH port mapping: connect via `ssh root@localhost -p 2222`
      - "2222:22"

  # Standalone mode: Uses code copied into the image (No host mounting)
  standalone:
    <<: *app-base
    container_name: standalone
    volumes:
      - ${USERPROFILE}/.ssh/id_ed25519.pub:/tmp/id_ed25519.pub:ro
    ports:
      - "2223:22"
    profiles:
      - standalone