[package]
name = "veloq-driver-uring"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
test-hooks = ["veloq-driver-core/test-hooks"]
std = [
    "veloq-std/std",
    "veloq-driver-core/std",
    "veloq-buf/std",
    "veloq-wheel/std",
]
loom = [
    "veloq-std/loom",
    "veloq-driver-core/loom",
    "veloq-buf/loom",
    "veloq-wheel/loom",
]

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
veloq-std.workspace = true
veloq-io-uring.workspace = true
veloq-driver-core.workspace = true
veloq-buf.workspace = true
veloq-wheel.workspace = true

crossbeam-queue.workspace = true
tracing.workspace = true
diagweave.workspace = true

libc.workspace = true

[lints]
workspace = true
