[package]
name = "veloq"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[features]
default = []
test-hooks = ["veloq-driver-native/test-hooks"]
std = [
    "veloq-std/std",
    "veloq-runtime/std",
    "veloq-buf/std",
    "veloq-driver-native/std",
    "veloq-blocking/std",
    "veloq-sync/std",
    "veloq-local/std",
    "veloq-waker/std",
]
loom = [
    "veloq-std/loom",
    "veloq-runtime/loom",
    "veloq-buf/loom",
    "veloq-driver-native/loom",
    "veloq-blocking/loom",
    "veloq-sync/loom",
    "veloq-local/loom",
    "veloq-waker/loom",
]

[dependencies]
veloq-runtime.workspace = true
veloq-buf.workspace = true
veloq-driver-native.workspace = true
veloq-blocking.workspace = true
veloq-sync.workspace = true
veloq-local.workspace = true
veloq-waker.workspace = true
veloq-std.workspace = true

futures-core.workspace = true
tracing.workspace = true
diagweave.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
criterion.workspace = true
futures-core.workspace = true
futures-util.workspace = true

[lints]
workspace = true

[[bench]]
name = "fs_benchmark"
harness = false
