[package]
name = "veloq-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
veloq-waker.workspace = true
veloq-intrusive-linklist.workspace = true
veloq-tls.workspace = true
veloq-std.workspace = true
veloq-storage.workspace = true

crossbeam-queue.workspace = true
numaperf-topo = "0.1"
crossbeam-deque.workspace = true

diagweave.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
veloq-futex.workspace = true

[features]
default = []
loom = [
    "veloq-intrusive-linklist/loom",
    "veloq-waker/loom",
    "veloq-tls/loom",
    "veloq-storage/loom",
    "veloq-std/loom",
]
std = [
    "veloq-intrusive-linklist/std",
    "veloq-waker/std",
    "veloq-storage/std",
    "veloq-std/std",
]

[lints]
workspace = true

[dev-dependencies]
trybuild = "1.0"
loom.workspace = true
