[alias]
xtest-linux = "run --package xtest-runner -- --task test --target linux --count 20 --quiet"
xtest-windows = "run --package xtest-runner -- --task test --target windows --count 20 --quiet"
xfmt = "fmt --all"
xclippy-linux = "run --package xtest-runner -- --task clippy --target linux --quiet"
xcheck-linux = "run --package xtest-runner -- --task check --target linux --quiet"
xclippy-windows = "run --package xtest-runner -- --task clippy --target windows --quiet"
xcheck-windows = "run --package xtest-runner -- --task check --target windows --quiet"
