[alias]
xtest-linux = "run --package xtest-runner -- --target linux --count 20 --quiet"
xtest-windows = "run --package xtest-runner -- --target windows --count 20 --quiet"
xfmt = "fmt --all -- --check"
xclippy = "clippy --all-targets -- -D warnings"
xcheck = "check"
xclippy-win = "clippy --all-targets --target x86_64-pc-windows-gnu -- -D warnings"
xcheck-win = "check --target x86_64-pc-windows-gnu"
