[package]
name = "veloq-driver-native"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
test-hooks = [
    "veloq-driver-core/test-hooks",
    "veloq-driver-uring/test-hooks",
    "veloq-driver-iocp/test-hooks",
]
std = [
    "veloq-std/std",
    "veloq-driver-uring/std",
    "veloq-driver-iocp/std",
    "veloq-driver-core/std",
    "veloq-waker/std",
    "veloq-buf/std",
    "veloq-blocking/std",
]
loom = [
    "veloq-std/loom",
    "veloq-driver-uring/loom",
    "veloq-driver-iocp/loom",
    "veloq-driver-core/loom",
    "veloq-waker/loom",
    "veloq-buf/loom",
    "veloq-blocking/loom",
]

[dependencies]
veloq-std.workspace = true
veloq-driver-core.workspace = true
veloq-waker.workspace = true
veloq-buf.workspace = true
veloq-wheel.workspace = true
veloq-blocking.workspace = true

futures-core.workspace = true
diagweave.workspace = true

crossbeam-utils.workspace = true
crossbeam-queue.workspace = true
tracing.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
libc.workspace = true
veloq-driver-uring.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys.workspace = true
veloq-driver-iocp.workspace = true

[lints]
workspace = true
